name: Docker CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

<<<<<<< HEAD
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: mammu0292/my-python-app:latest
=======
      - name: Build Docker image
        run: docker build -t my-python-app .
>>>>>>> 29d4a0f916601c1711673ccf7fa0eb665491b37e
